server:
#  port: 8762
  port: 8763
spring:
  application:
    name: hystrix-turbine-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

# dashboard配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"

turbine:
  app-config: eureka-client
  aggregator:
    clusterConfig: default
  clusterNameExpression: new String("default")
  combine-host: true
  instanceUrlSuffix:
    default: actuator/hystrix.stream
