# 服务名
spring:
  application:
    name: account-service
  # seata分组
  cloud:
    alibaba:
      seata:
        tx-service-group: default
  # 数据源
#  datasource:
#    url: jdbc:mysql://localhost:3306/test
#    username: root
#    password: 123456
#    type: com.zaxxer.hikari.HikariDataSource
#    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    url: jdbc:mysql://localhost:3306/seata_demo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver

# eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/